=== flare-foundation/fasset-bots/packages/fasset-bots-core/run-config/schema/bot-config.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "additionalProperties": false,
    "definitions": {
        "BotFAssetInfo": {
            "additionalProperties": false,
            "properties": {
                "chainId": {
                    "type": "string"
                },
                "fAssetSymbol": {
                    "type": "string"
                },
                "inTestnet": {
                    "type": "boolean"
                },
                "indexerUrl": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "priceChangeEmitter": {
                    "type": "string"
                },
                "symbol": {
                    "type": "string"
                },
                "walletUrl": {
                    "type": "string"
                }
            },
            "required": [
                "chainId",
                "fAssetSymbol",
                "name",
                "symbol"
            ],
            "type": "object"
        },
        "BotStrategyDefinition": {
            "additionalProperties": false,
            "properties": {
                "className": {
                    "type": "string"
                },
                "config": {}
            },
            "required": [
                "className"
            ],
            "type": "object"
        },
        "DatabaseType": {
            "enum": [
                "mysql",
                "postgresql",
                "sqlite"
            ],
            "type": "string"
        },
        "NativeChainInfo": {
            "additionalProperties": false,
            "properties": {
                "finalizationBlocks": {
                    "type": "number"
                },
                "readLogsChunkSize": {
                    "type": "number"
                }
            },
            "required": [
                "finalizationBlocks",
                "readLogsChunkSize"
            ],
            "type": "object"
        },
        "OrmConfigOptions": {
            "additionalProperties": {},
            "properties": {
                "charset": {
                    "type": "string"
                },
                "clientUrl": {
                    "type": "string"
                },
                "dbName": {
                    "type": "string"
                },
                "debug": {
                    "type": "boolean"
                },
                "host": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "port": {
                    "type": "number"
                },
                "schemaUpdate": {
                    "enum": [
                        "full",
                        "none",
                        "recreate",
                        "safe"
                    ],
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/DatabaseType"
                },
                "user": {
                    "type": "string"
                }
            },
            "required": [
                "type"
            ],
            "type": "object"
        }
    },
    "properties": {
        "$schema": {
            "type": "string"
        },
        "alertsUrl": {
            "type": "string"
        },
        "assetManagerController": {
            "type": "string"
        },
        "attestationProviderUrls": {
            "items": {
                "type": "string"
            },
            "type": "array"
        },
        "challengeStrategy": {
            "$ref": "#/definitions/BotStrategyDefinition"
        },
        "contractsJsonFile": {
            "type": "string"
        },
        "fAssetInfos": {
            "items": {
                "$ref": "#/definitions/BotFAssetInfo"
            },
            "type": "array"
        },
        "liquidationStrategy": {
            "$ref": "#/definitions/BotStrategyDefinition"
        },
        "loopDelay": {
            "type": "number"
        },
        "nativeChainInfo": {
            "$ref": "#/definitions/NativeChainInfo"
        },
        "ormOptions": {
            "$ref": "#/definitions/OrmConfigOptions"
        },
        "prioritizeAddressUpdater": {
            "type": "boolean"
        },
        "rpcUrl": {
            "type": "string"
        },
        "walletOptions": {
            "additionalProperties": false,
            "properties": {
                "blockOffset": {
                    "type": "number"
                },
                "feeIncrease": {
                    "type": "number"
                },
                "retries": {
                    "type": "number"
                }
            },
            "type": "object"
        }
    },
    "required": [
        "fAssetInfos",
        "loopDelay",
        "nativeChainInfo",
        "prioritizeAddressUpdater",
        "rpcUrl"
    ],
    "type": "object"
}

=== flare-foundation/fasset-bots/packages/fasset-bots-core/test/test-utils/run-config-test/run-simplified-config-coston-with-contracts.json
{
    "loopDelay": 10000,
    "contractsJsonFile": "../../../fasset-deployment/coston.json",
    "prioritizeAddressUpdater": false,
    "nativeChainInfo": {
        "finalizationBlocks": 6,
        "readLogsChunkSize": 10
    },
    "fAssetInfos": [
        {
            "chainId": "testXRP",
            "name": "Test XRP",
            "symbol": "testXRP",
            "fAssetSymbol": "FtestXRP",
            "indexerUrl": "https://attestation-coston.aflabs.net/verifier/xrp"
        },
        {
            "chainId": "testXRP",
            "name": "Fake XRP",
            "symbol": "fakeXRP",
            "fAssetSymbol": "FfakeXRP",
            "indexerUrl": "https://attestation-coston.aflabs.net/verifier/xrp",
            "priceChangeEmitter": "FakePriceReader"
        }
    ],
    "rpcUrl": "https://coston-api.flare.network/ext/C/rpc",
    "attestationProviderUrls": [
        "https://attestation-coston.aflabs.net/attestation-client"
    ]
}
